create table customer
(
    id            bigint generated by default as identity,
    email         varchar(255),
    name          varchar(255),
    password      varchar(255),
    recovery_code varchar(255),
    recovery_date timestamp(6),
    status        smallint,
    primary key (id),
    constraint ukdwk6cx0afu8bs9o4t536v1j5v
        unique (email),
    constraint customer_status_check
        check ((status >= 0) AND (status <= 1))
);

alter table customer
    owner to postgres;

create table role
(
    role_id integer generated by default as identity,
    name    varchar(25) not null,
    status  smallint    not null,
    primary key (role_id),
    constraint uk8sewwnpamngi6b1dwaa88askk
        unique (name),
    constraint role_status_check
        check ((status >= 0) AND (status <= 1))
);

alter table role
    owner to postgres;

create table customer_role
(
    customer_id bigint  not null,
    role_id     integer not null,
    constraint fkmwml8muyov9xhw4423lp88n2u
        foreign key (role_id) references role,
    constraint fkipr3etk2mjwkv6ahb4x4vwqy3
        foreign key (customer_id) references customer
);

alter table customer_role
    owner to postgres;

create table token
(
    id          bigint generated by default as identity,
    expired     boolean not null,
    revoked     boolean not null,
    token       varchar(255),
    token_type  varchar(255),
    customer_id bigint,
    primary key (id),
    constraint ukpddrhgwxnms2aceeku9s2ewy5
        unique (token),
    constraint fkke9j5rnuwqfkmnyyfa9k2p3ug
        foreign key (customer_id) references customer,
    constraint token_token_type_check
        check ((token_type)::text = 'BEARER'::text)
    );

alter table token
    owner to postgres;

create table discount
(
    id_order bigint not null,
    discount integer
);

alter table discount
    owner to postgres;

create table orders
(
    id             bigint generated by default as identity,
    address        varchar(255) not null,
    city           varchar(255) not null,
    created_at     timestamp(6),
    description    varchar(255),
    email_customer varchar(255) not null,
    order_code     varchar(255) not null,
    payment_method smallint     not null,
    status         smallint     not null,
    total          integer      not null,
    updated_at     timestamp(6),
    primary key (id),
    constraint orders_payment_method_check
        check ((payment_method >= 0) AND (payment_method <= 3)),
    constraint orders_status_check
        check ((status >= 0) AND (status <= 3))
);

alter table orders
    owner to postgres;

create table order_product
(
    id         bigint generated by default as identity,
    color      varchar(255),
    discount   integer,
    id_product bigint       not null,
    name       varchar(255) not null,
    quantity   integer      not null,
    size       varchar(255),
    total      integer      not null,
    unit_price integer      not null,
    id_order   bigint       not null,
    primary key (id),
    constraint fkg3uugag7e9dxyx74h2tftyp1c
        foreign key (id_order) references orders
);

alter table order_product
    owner to postgres;

create table discount_order
(
    id_order bigint not null,
    discount integer,
    constraint fkatc97mailoje0xlmiceeme3ev
        foreign key (id_order) references orders
);

alter table discount_order
    owner to postgres;

create table category
(
    id     bigint generated by default as identity,
    name   varchar(50) not null,
    status smallint    not null,
    primary key (id),
    constraint uk46ccwnsi9409t36lurvtyljak
        unique (name),
    constraint category_status_check
        check ((status >= 0) AND (status <= 1))
);

alter table category
    owner to postgres;

create table product
(
    id          bigint generated by default as identity,
    created_at  timestamp(6) not null,
    description varchar(250),
    discount    integer,
    name        varchar(50)  not null,
    price       integer      not null,
    status      smallint     not null,
    updated_at  timestamp(6),
    category_id bigint       not null,
    primary key (id),
    constraint ukjmivyxk9rmgysrmsqw15lqr5b
        unique (name),
    constraint fk1mtsbur82frn64de7balymq9s
        foreign key (category_id) references category,
    constraint product_status_check
        check ((status >= 0) AND (status <= 1))
);

alter table product
    owner to postgres;

create table product_colors
(
    product_id bigint not null,
    colors     varchar(255),
    constraint fkrxtutgloy8nt7w2k50fnmu3ji
        foreign key (product_id) references product
);

alter table product_colors
    owner to postgres;

create table product_images_url
(
    product_id bigint not null,
    images_url varchar(255),
    constraint fk4uuohcjv5iu6gfin9kqbxdipq
        foreign key (product_id) references product
);

alter table product_images_url
    owner to postgres;

create table product_sizes
(
    product_id bigint not null,
    sizes      varchar(255),
    constraint fk4w69qsh5hd062xv3hqkpgpdpu
        foreign key (product_id) references product
);

alter table product_sizes
    owner to postgres;

